// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75SviM_MxTbLUBP9DGCT4Q0m7RFqHgLw',
    appId: '1:558984441603:web:64ed7bc761a3e21cbfc336',
    messagingSenderId: '558984441603',
    projectId: 'todoapp-79696',
    authDomain: 'todoapp-79696.firebaseapp.com',
    storageBucket: 'todoapp-79696.appspot.com',
    measurementId: 'G-J12528P7N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxRLydCp9gm0CpZM2mH-99e1EVrSoLVE',
    appId: '1:558984441603:android:0c4d8eb288543543bfc336',
    messagingSenderId: '558984441603',
    projectId: 'todoapp-79696',
    storageBucket: 'todoapp-79696.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8XLIFMCa0eF0lSatrKNGIUjO4NOuOwg',
    appId: '1:558984441603:ios:ab248627ee63b91dbfc336',
    messagingSenderId: '558984441603',
    projectId: 'todoapp-79696',
    storageBucket: 'todoapp-79696.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8XLIFMCa0eF0lSatrKNGIUjO4NOuOwg',
    appId: '1:558984441603:ios:d5082a242fe3b384bfc336',
    messagingSenderId: '558984441603',
    projectId: 'todoapp-79696',
    storageBucket: 'todoapp-79696.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
